# Generated by Django 3.2.8 on 2021-10-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_in_db_timestamp', models.DateTimeField(auto_now_add=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('age_bucket', models.CharField(blank=True, max_length=100, null=True)),
                ('airlines', models.CharField(blank=True, max_length=100, null=True)),
                ('airlines_names', models.CharField(blank=True, max_length=100, null=True)),
                ('bags', models.CharField(blank=True, max_length=100, null=True)),
                ('bags_bucket', models.CharField(blank=True, max_length=100, null=True)),
                ('haul', models.CharField(blank=True, max_length=100, null=True)),
                ('bid', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_original', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('customer_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('fare_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('has_score', models.BooleanField()),
                ('review_id', models.CharField(blank=True, max_length=250, null=True)),
                ('nomad', models.BooleanField()),
                ('partner', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('score_category', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('theme_label', models.ManyToManyField(blank=True, related_name='theme_labels', to='feedback.Theme_label')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
