# Generated by Django 3.2.8 on 2021-10-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nps',
            name='theme_label',
        ),
        migrations.AddField(
            model_name='theme_label',
            name='nps',
            field=models.ManyToManyField(blank=True, related_name='nps_labels', to='feedback.NPS'),
        ),
    ]
